# Generated by Django 4.0.1 on 2022-01-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginaudit',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'Success'), ('F', 'Failed')], default='S', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userloginaudit',
            name='user_agent_info',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
