# Generated by Django 4.0.1 on 2022-01-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userloginaudit_status_userloginaudit_user_agent_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroccupation',
            name='ocpSalary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
